name: package next.js project and push to docker
on: push

jobs:
  bun-build:
    name: bun build job
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: login in Dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: build and push to dockerhub
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ngc2207/nextjs-litchi:latest
